// Общий список языков для использования во всех компонентах
export const languageOptions = [
  { value: 'be', label: 'беларуская' },
  { value: 'de', label: 'Deutsch' },
  { value: 'en', label: 'English' },
  { value: 'es', label: 'español' },
  { value: 'pt', label: 'Português' },
  { value: 'ru', label: 'Русский' },
  { value: 'uk', label: 'Українська' },
  { value: 'zh', label: '简体中文' },
  { value: 'af', label: 'Afrikaans' },
  { value: 'ar', label: 'العربيّة' },
  { value: 'ast', label: 'asturianu' },
  { value: 'az', label: 'Azərbaycanca' },
  { value: 'bg', label: 'български' },
  { value: 'bn', label: 'বাংলা' },
  { value: 'br', label: 'brezhoneg' },
  { value: 'bs', label: 'bosanski' },
  { value: 'ca', label: 'català' },
  { value: 'cs', label: 'česky' },
  { value: 'cy', label: 'Cymraeg' },
  { value: 'da', label: 'dansk' },
  { value: 'el', label: 'Ελληνικά' },
  { value: 'en-AU', label: 'Australian English' },
  { value: 'en-GB', label: 'British English' },
  { value: 'eo', label: 'Esperanto' },
  { value: 'es-AR', label: 'español de Argentina' },
  { value: 'es-CO', label: 'español de Colombia' },
  { value: 'es-MX', label: 'español de Mexico' },
  { value: 'es-NI', label: 'español de Nicaragua' },
  { value: 'es-VE', label: 'español de Venezuela' },
  { value: 'et', label: 'eesti' },
  { value: 'eu', label: 'Basque' },
  { value: 'fa', label: 'فارسی' },
  { value: 'fi', label: 'suomi' },
  { value: 'fr', label: 'français' },
  { value: 'fy', label: 'frysk' },
  { value: 'ga', label: 'Gaeilge' },
  { value: 'gd', label: 'Gàidhlig' },
  { value: 'gl', label: 'galego' },
  { value: 'he', label: 'עברית' },
  { value: 'hi', label: 'Hindi' },
  { value: 'hr', label: 'Hrvatski' },
  { value: 'hu', label: 'Magyar' },
  { value: 'ia', label: 'Interlingua' },
  { value: 'id', label: 'Bahasa Indonesia' },
  { value: 'io', label: 'ido' },
  { value: 'is', label: 'Íslenska' },
  { value: 'it', label: 'italiano' },
  { value: 'ja', label: '日本語' },
  { value: 'ka', label: 'ქართული' },
  { value: 'kk', label: 'Қазақ' },
  { value: 'km', label: 'Khmer' },
  { value: 'kn', label: 'Kannada' },
  { value: 'ko', label: '한국어' },
  { value: 'lb', label: 'Lëtzebuergesch' },
  { value: 'lt', label: 'Lietuviškai' },
  { value: 'lv', label: 'latviešu' },
  { value: 'mk', label: 'Македонски' },
  { value: 'ml', label: 'Malayalam' },
  { value: 'mn', label: 'Mongolian' },
  { value: 'mr', label: 'मराठी' },
  { value: 'my', label: 'မြန်မာဘာသာ' },
  { value: 'nb', label: 'norsk (bokmål)' },
  { value: 'ne', label: 'नेपाली' },
  { value: 'nl', label: 'Nederlands' },
  { value: 'nn', label: 'norsk (nynorsk)' },
  { value: 'os', label: 'Ирон' },
  { value: 'pa', label: 'Punjabi' },
  { value: 'pl', label: 'polski' },
  { value: 'pt-BR', label: 'Português Brasileiro' },
  { value: 'ro', label: 'Română' },
  { value: 'sk', label: 'Slovensky' },
  { value: 'sl', label: 'Slovenščina' },
  { value: 'sq', label: 'shqip' },
  { value: 'sr', label: 'српски' },
  { value: 'sr-Latn', label: 'srpski (latinica)' },
  { value: 'sv', label: 'svenska' },
  { value: 'sw', label: 'Kiswahili' },
  { value: 'ta', label: 'தமிழ்' },
  { value: 'te', label: 'తెలుగు' },
  { value: 'th', label: 'ภาษาไทย' },
  { value: 'tr', label: 'Türkçe' },
  { value: 'tt', label: 'Татарча' },
  { value: 'udm', label: 'Удмурт' },
  { value: 'ur', label: 'اردو' },
  { value: 'vi', label: 'Tiếng Việt' },
  { value: 'zh-TW', label: '繁體中文' }
];

// Функция для получения названия языка по коду
export const getLanguageName = (languageCode) => {
  const language = languageOptions.find(opt => opt.value === languageCode);
  return language ? language.label : languageCode || 'Unknown';
}; 